from . import hrEmloyee
from . import HrEmployeePayrollDispatch
from . import resPartnerbank
from . import resCompany
from . import hr_holidays
from . import hr_holidays_provision
from . import hr_holidays_recovery
from . import hr_holidays_planning
from . import hrContract
from . import hrPayroll
from . import res_config_setting
